// Complete car database for luxury car dealership
// This includes all luxury cars and comprehensive regular car collection

const regularCars = [
    // Toyota
    { name: "Camry", brand: "Toyota", category: "regular", price: "$26,000-$35,000", image: "/api/placeholder/600/400", info: "Midsize sedan, 2.5L I4 (203 HP) or 3.5L V6 (301 HP) | Reliable and efficient", year: 2023, specifications: { engine: "2.5L I4 / 3.5L V6", power: "203-301 HP", transmission: "8-Speed Automatic", fuelType: "Regular Gasoline" }, features: ["Toyota Safety Sense 2.0", "Wireless Charging", "JBL Audio", "Panoramic Sunroof"], isActive: true, featured: false },
    { name: "Corolla", brand: "Toyota", category: "regular", price: "$21,000-$28,000", image: "/api/placeholder/600/400", info: "Compact sedan or hatchback, 2.0L I4 (169 HP) | Excellent fuel economy", year: 2023, specifications: { engine: "2.0L I4", power: "169 HP", transmission: "CVT", fuelType: "Regular Gasoline" }, features: ["Toyota Safety Sense 2.0", "Apple CarPlay", "LED Headlights", "Automatic Climate Control"], isActive: true, featured: false },
    { name: "RAV4", brand: "Toyota", category: "regular", price: "$28,000-$38,000", image: "/api/placeholder/600/400", info: "Compact SUV, 2.5L I4 (203 HP) or hybrid (219 HP) | All-wheel drive available", year: 2023, specifications: { engine: "2.5L I4 / Hybrid", power: "203-219 HP", transmission: "8-Speed Automatic", fuelType: "Regular Gasoline / Hybrid" }, features: ["All-Wheel Drive", "Toyota Safety Sense 2.0", "Wireless Charging", "Power Liftgate"], isActive: true, featured: false },
    { name: "Highlander", brand: "Toyota", category: "regular", price: "$36,000-$52,000", image: "/api/placeholder/600/400", info: "Midsize SUV, 2.4L I4 (265 HP) or hybrid (243 HP) | Three-row seating", year: 2023, specifications: { engine: "2.4L I4 Turbo / Hybrid", power: "243-265 HP", transmission: "8-Speed Automatic", fuelType: "Regular Gasoline / Hybrid" }, features: ["All-Wheel Drive", "Three-Row Seating", "JBL Audio", "Panoramic Sunroof"], isActive: true, featured: false },
    { name: "Prius", brand: "Toyota", category: "regular", price: "$25,000-$34,000", image: "/api/placeholder/600/400", info: "Hybrid compact car, 1.8L I4 (121 HP) or plug-in hybrid (220 HP) | Outstanding fuel economy", year: 2023, specifications: { engine: "1.8L I4 Hybrid", power: "121-220 HP", transmission: "CVT", fuelType: "Hybrid / Plug-in Hybrid" }, features: ["Hybrid Technology", "Toyota Safety Sense 2.0", "Wireless Charging", "Solar Roof"], isActive: true, featured: false },

    // Honda
    { name: "Civic", brand: "Honda", category: "regular", price: "$23,000-$30,000", image: "/api/placeholder/600/400", info: "Compact sedan or hatchback, 2.0L I4 (158 HP) or 1.5L turbo (180 HP) | Sporty and efficient", year: 2023, specifications: { engine: "2.0L I4 / 1.5L Turbo", power: "158-180 HP", transmission: "CVT / 6-Speed Manual", fuelType: "Regular Gasoline" }, features: ["Honda Sensing", "Apple CarPlay", "LED Headlights", "Wireless Charging"], isActive: true, featured: false },
    { name: "Accord", brand: "Honda", category: "regular", price: "$27,000-$38,000", image: "/api/placeholder/600/400", info: "Midsize sedan, 1.5L turbo (192 HP) or 2.0L turbo (252 HP) | Premium comfort", year: 2023, specifications: { engine: "1.5L Turbo / 2.0L Turbo", power: "192-252 HP", transmission: "CVT / 10-Speed Automatic", fuelType: "Regular Gasoline" }, features: ["Honda Sensing", "Wireless Charging", "Bose Audio", "Head-Up Display"], isActive: true, featured: false },
    { name: "CR-V", brand: "Honda", category: "regular", price: "$28,000-$38,000", image: "/api/placeholder/600/400", info: "Compact SUV, 1.5L turbo (190 HP) or hybrid (212 HP) | Versatile and reliable", year: 2023, specifications: { engine: "1.5L Turbo / Hybrid", power: "190-212 HP", transmission: "CVT", fuelType: "Regular Gasoline / Hybrid" }, features: ["All-Wheel Drive", "Honda Sensing", "Power Tailgate", "Remote Start"], isActive: true, featured: false },
    { name: "HR-V", brand: "Honda", category: "regular", price: "$23,000-$30,000", image: "/api/placeholder/600/400", info: "Subcompact SUV, 2.0L I4 (158 HP) | Compact and efficient", year: 2023, specifications: { engine: "2.0L I4", power: "158 HP", transmission: "CVT", fuelType: "Regular Gasoline" }, features: ["All-Wheel Drive", "Honda Sensing", "Magic Seats", "Apple CarPlay"], isActive: true, featured: false },
    { name: "Odyssey", brand: "Honda", category: "regular", price: "$37,000-$52,000", image: "/api/placeholder/600/400", info: "Minivan, 3.5L V6 (280 HP) | Family-friendly with advanced features", year: 2023, specifications: { engine: "3.5L V6", power: "280 HP", transmission: "10-Speed Automatic", fuelType: "Regular Gasoline" }, features: ["Magic Slide Seats", "CabinWatch", "Vacuum Cleaner", "Entertainment System"], isActive: true, featured: false },

    // Ford
    { name: "Mustang", brand: "Ford", category: "regular", price: "$30,000-$60,000", image: "/api/placeholder/600/400", info: "Sports car, 2.3L turbo I4 (310 HP) or 5.0L V8 (450 HP) | American muscle icon", year: 2023, specifications: { engine: "2.3L Turbo I4 / 5.0L V8", power: "310-450 HP", transmission: "6-Speed Manual / 10-Speed Automatic", fuelType: "Premium Gasoline" }, features: ["Performance Package", "SYNC 4", "Recaro Seats", "Track Apps"], isActive: true, featured: true },
    { name: "Explorer", brand: "Ford", category: "regular", price: "$36,000-$55,000", image: "/api/placeholder/600/400", info: "Midsize SUV, 2.3L turbo I4 (300 HP) or 3.0L V6 (400 HP) | Three-row capability", year: 2023, specifications: { engine: "2.3L Turbo I4 / 3.0L V6", power: "300-400 HP", transmission: "10-Speed Automatic", fuelType: "Regular Gasoline" }, features: ["Intelligent 4WD", "Co-Pilot360", "SYNC 4", "Wireless Charging"], isActive: true, featured: false },
    { name: "F-150", brand: "Ford", category: "regular", price: "$33,000-$80,000", image: "/api/placeholder/600/400", info: "Full-size pickup, 3.3L V6 (290 HP) to 3.5L turbo V6 (450 HP) | America's best-selling truck", year: 2023, specifications: { engine: "3.3L V6 to 3.5L Turbo V6", power: "290-450 HP", transmission: "10-Speed Automatic", fuelType: "Regular Gasoline" }, features: ["Pro Trailer Backup Assist", "SYNC 4", "FordPass Connect", "Intelligent 4WD"], isActive: true, featured: false },
    { name: "Escape", brand: "Ford", category: "regular", price: "$26,000-$38,000", image: "/api/placeholder/600/400", info: "Compact SUV, 1.5L turbo I4 (181 HP) or 2.0L turbo (250 HP) | Efficient and versatile", year: 2023, specifications: { engine: "1.5L Turbo I4 / 2.0L Turbo", power: "181-250 HP", transmission: "8-Speed Automatic", fuelType: "Regular Gasoline" }, features: ["Intelligent 4WD", "Co-Pilot360", "SYNC 3", "Hands-Free Liftgate"], isActive: true, featured: false },

    // Chevrolet
    { name: "Malibu", brand: "Chevrolet", category: "regular", price: "$25,000-$35,000", image: "/api/placeholder/600/400", info: "Midsize sedan, 1.5L turbo I4 (160 HP) | Comfortable and efficient", year: 2023, specifications: { engine: "1.5L Turbo I4", power: "160 HP", transmission: "CVT", fuelType: "Regular Gasoline" }, features: ["Chevrolet Safety Assist", "Infotainment 3", "Wireless Charging", "Teen Driver"], isActive: true, featured: false },
    { name: "Traverse", brand: "Chevrolet", category: "regular", price: "$35,000-$50,000", image: "/api/placeholder/600/400", info: "Midsize SUV, 3.6L V6 (310 HP) | Three-row family hauler", year: 2023, specifications: { engine: "3.6L V6", power: "310 HP", transmission: "9-Speed Automatic", fuelType: "Regular Gasoline" }, features: ["All-Wheel Drive", "Chevrolet Safety Assist", "Infotainment 3", "Hands-Free Liftgate"], isActive: true, featured: false },
    { name: "Silverado 1500", brand: "Chevrolet", category: "regular", price: "$36,000-$70,000", image: "/api/placeholder/600/400", info: "Full-size pickup, 2.7L turbo I4 (310 HP) to 6.2L V8 (420 HP) | Dependable workhorse", year: 2023, specifications: { engine: "2.7L Turbo I4 to 6.2L V8", power: "310-420 HP", transmission: "8-10 Speed Automatic", fuelType: "Regular Gasoline" }, features: ["Trailering Package", "Chevrolet Safety Assist", "Infotainment 3", "Multi-Flex Tailgate"], isActive: true, featured: false },
    { name: "Equinox", brand: "Chevrolet", category: "regular", price: "$26,000-$35,000", image: "/api/placeholder/600/400", info: "Compact SUV, 1.5L turbo I4 (175 HP) | Practical and affordable", year: 2023, specifications: { engine: "1.5L Turbo I4", power: "175 HP", transmission: "6-Speed Automatic", fuelType: "Regular Gasoline" }, features: ["All-Wheel Drive", "Chevrolet Safety Assist", "Infotainment 3", "Hands-Free Liftgate"], isActive: true, featured: false },
    { name: "Trailblazer", brand: "Chevrolet", category: "regular", price: "$22,000-$30,000", image: "/api/placeholder/600/400", info: "Subcompact SUV, 1.2L turbo I3 (137 HP) or 1.3L turbo (155 HP) | Urban-friendly", year: 2023, specifications: { engine: "1.2L Turbo I3 / 1.3L Turbo", power: "137-155 HP", transmission: "CVT / 9-Speed Automatic", fuelType: "Regular Gasoline" }, features: ["All-Wheel Drive", "Chevrolet Safety Assist", "Infotainment 3", "Cargo Management"], isActive: true, featured: false },

    // Tesla
    { name: "Model 3", brand: "Tesla", category: "regular", price: "$40,000-$55,000", image: "/api/placeholder/600/400", info: "Electric sedan, 283–450 HP, 272–358-mile range | Revolutionary electric performance", year: 2023, specifications: { engine: "Electric Motor(s)", power: "283-450 HP", transmission: "Single-Speed", fuelType: "Electric" }, features: ["Autopilot", "Over-the-Air Updates", "Supercharging", "Premium Interior"], isActive: true, featured: true },
    { name: "Model Y", brand: "Tesla", category: "regular", price: "$45,000-$60,000", image: "/api/placeholder/600/400", info: "Electric SUV, 283–456 HP, 279–330-mile range | Versatile electric SUV", year: 2023, specifications: { engine: "Electric Motor(s)", power: "283-456 HP", transmission: "Single-Speed", fuelType: "Electric" }, features: ["Autopilot", "Over-the-Air Updates", "Supercharging", "Glass Roof"], isActive: true, featured: true },
    { name: "Model S", brand: "Tesla", category: "regular", price: "$75,000-$100,000", image: "/api/placeholder/600/400", info: "Electric sedan, 670 HP, 405-mile range | Flagship luxury electric sedan", year: 2023, specifications: { engine: "Electric Motors", power: "670 HP", transmission: "Single-Speed", fuelType: "Electric" }, features: ["Plaid Powertrain", "17-inch Touchscreen", "Autopilot", "Premium Audio"], isActive: true, featured: true },
    { name: "Model X", brand: "Tesla", category: "regular", price: "$80,000-$110,000", image: "/api/placeholder/600/400", info: "Electric SUV, 670 HP, 348-mile range | Falcon wing doors and luxury", year: 2023, specifications: { engine: "Electric Motors", power: "670 HP", transmission: "Single-Speed", fuelType: "Electric" }, features: ["Falcon Wing Doors", "17-inch Touchscreen", "Autopilot", "Seven Seats"], isActive: true, featured: true },

    // Hyundai
    { name: "Elantra", brand: "Hyundai", category: "regular", price: "$20,000-$28,000", image: "/api/placeholder/600/400", info: "Compact sedan, 2.0L I4 (147 HP) or 1.6L turbo (201 HP) | Value and reliability", year: 2023, specifications: { engine: "2.0L I4 / 1.6L Turbo", power: "147-201 HP", transmission: "CVT / 7-Speed DCT", fuelType: "Regular Gasoline" }, features: ["Hyundai SmartSense", "Wireless Charging", "Digital Cockpit", "BlueLink"], isActive: true, featured: false },
    { name: "Sonata", brand: "Hyundai", category: "regular", price: "$25,000-$35,000", image: "/api/placeholder/600/400", info: "Midsize sedan, 2.5L I4 (191 HP) or 1.6L turbo (180 HP) | Sophisticated design", year: 2023, specifications: { engine: "2.5L I4 / 1.6L Turbo", power: "180-191 HP", transmission: "8-Speed Automatic", fuelType: "Regular Gasoline" }, features: ["Hyundai SmartSense", "Digital Key", "Bose Audio", "Wireless Charging"], isActive: true, featured: false },
    { name: "Tucson", brand: "Hyundai", category: "regular", price: "$26,000-$38,000", image: "/api/placeholder/600/400", info: "Compact SUV, 2.5L I4 (187 HP) or hybrid (226 HP) | Bold and efficient", year: 2023, specifications: { engine: "2.5L I4 / Hybrid", power: "187-226 HP", transmission: "8-Speed Automatic", fuelType: "Regular Gasoline / Hybrid" }, features: ["All-Wheel Drive", "Hyundai SmartSense", "Digital Cockpit", "Hands-Free Liftgate"], isActive: true, featured: false },
    { name: "Santa Fe", brand: "Hyundai", category: "regular", price: "$28,000-$42,000", image: "/api/placeholder/600/400", info: "Midsize SUV, 2.5L I4 (191 HP) or hybrid (225 HP) | Family-focused", year: 2023, specifications: { engine: "2.5L I4 / Hybrid", power: "191-225 HP", transmission: "8-Speed Automatic", fuelType: "Regular Gasoline / Hybrid" }, features: ["All-Wheel Drive", "Hyundai SmartSense", "Three-Row Seating", "Calligraphy Trim"], isActive: true, featured: false },
    { name: "Palisade", brand: "Hyundai", category: "regular", price: "$35,000-$50,000", image: "/api/placeholder/600/400", info: "Large SUV, 3.8L V6 (291 HP) | Premium three-row SUV", year: 2023, specifications: { engine: "3.8L V6", power: "291 HP", transmission: "8-Speed Automatic", fuelType: "Regular Gasoline" }, features: ["All-Wheel Drive", "Captain's Chairs", "Hyundai SmartSense", "Harman Kardon Audio"], isActive: true, featured: false },

    // Nissan
    { name: "Altima", brand: "Nissan", category: "regular", price: "$25,000-$35,000", image: "/api/placeholder/600/400", info: "Midsize sedan, 2.5L I4 (188 HP) or 2.0L turbo (248 HP) | Intelligent mobility", year: 2023, specifications: { engine: "2.5L I4 / 2.0L Turbo", power: "188-248 HP", transmission: "CVT", fuelType: "Regular Gasoline" }, features: ["Nissan Safety Shield 360", "ProPILOT Assist", "NissanConnect", "Intelligent AWD"], isActive: true, featured: false },
    { name: "Sentra", brand: "Nissan", category: "regular", price: "$20,000-$25,000", image: "/api/placeholder/600/400", info: "Compact sedan, 2.0L I4 (149 HP) | Affordable and efficient", year: 2023, specifications: { engine: "2.0L I4", power: "149 HP", transmission: "CVT", fuelType: "Regular Gasoline" }, features: ["Nissan Safety Shield 360", "NissanConnect", "Apple CarPlay", "Intelligent Key"], isActive: true, featured: false },
    { name: "Rogue", brand: "Nissan", category: "regular", price: "$27,000-$38,000", image: "/api/placeholder/600/400", info: "Compact SUV, 1.5L turbo I3 (201 HP) | Versatile and practical", year: 2023, specifications: { engine: "1.5L Turbo I3", power: "201 HP", transmission: "CVT", fuelType: "Regular Gasoline" }, features: ["Intelligent AWD", "ProPILOT Assist", "Divide-N-Hide Cargo", "NissanConnect"], isActive: true, featured: false },
    { name: "Pathfinder", brand: "Nissan", category: "regular", price: "$34,000-$50,000", image: "/api/placeholder/600/400", info: "Midsize SUV, 3.5L V6 (284 HP) | Adventure-ready family SUV", year: 2023, specifications: { engine: "3.5L V6", power: "284 HP", transmission: "9-Speed Automatic", fuelType: "Regular Gasoline" }, features: ["Intelligent 4WD", "Tri-Zone Climate", "NissanConnect", "Tow Mode"], isActive: true, featured: false },
    { name: "Maxima", brand: "Nissan", category: "regular", price: "$38,000-$45,000", image: "/api/placeholder/600/400", info: "Midsize sedan, 3.5L V6 (300 HP) | Performance-oriented sedan", year: 2023, specifications: { engine: "3.5L V6", power: "300 HP", transmission: "CVT", fuelType: "Premium Gasoline" }, features: ["Sport-Tuned Suspension", "NissanConnect", "Bose Audio", "Intelligent Key"], isActive: true, featured: false },

    // Volkswagen
    { name: "Jetta", brand: "Volkswagen", category: "regular", price: "$20,000-$28,000", image: "/api/placeholder/600/400", info: "Compact sedan, 1.5L turbo I4 (158 HP) | German engineering", year: 2023, specifications: { engine: "1.5L Turbo I4", power: "158 HP", transmission: "8-Speed Automatic", fuelType: "Regular Gasoline" }, features: ["IQ.DRIVE", "Digital Cockpit", "App-Connect", "Leatherette Seating"], isActive: true, featured: false },
    { name: "Tiguan", brand: "Volkswagen", category: "regular", price: "$27,000-$38,000", image: "/api/placeholder/600/400", info: "Compact SUV, 2.0L turbo I4 (184 HP) | European sophistication", year: 2023, specifications: { engine: "2.0L Turbo I4", power: "184 HP", transmission: "8-Speed Automatic", fuelType: "Regular Gasoline" }, features: ["4MOTION AWD", "IQ.DRIVE", "Digital Cockpit", "Three-Row Seating"], isActive: true, featured: false },
    { name: "Golf GTI", brand: "Volkswagen", category: "regular", price: "$30,000-$40,000", image: "/api/placeholder/600/400", info: "Hot hatch, 2.0L turbo I4 (241 HP) | Performance icon", year: 2023, specifications: { engine: "2.0L Turbo I4", power: "241 HP", transmission: "6-Speed Manual / 7-Speed DSG", fuelType: "Premium Gasoline" }, features: ["Performance Package", "DCC Adaptive Suspension", "Digital Cockpit", "Plaid Seats"], isActive: true, featured: true },
    { name: "Atlas", brand: "Volkswagen", category: "regular", price: "$35,000-$50,000", image: "/api/placeholder/600/400", info: "Midsize SUV, 2.0L turbo I4 (235 HP) or 3.6L V6 (276 HP) | Spacious and refined", year: 2023, specifications: { engine: "2.0L Turbo I4 / 3.6L V6", power: "235-276 HP", transmission: "8-Speed Automatic", fuelType: "Regular Gasoline" }, features: ["4MOTION AWD", "Three-Row Seating", "Digital Cockpit", "Captain's Chairs"], isActive: true, featured: false },

    // Subaru
    { name: "Outback", brand: "Subaru", category: "regular", price: "$28,000-$40,000", image: "/api/placeholder/600/400", info: "Midsize wagon, 2.5L flat-4 (182 HP) or 2.4L turbo (260 HP) | Adventure-ready", year: 2023, specifications: { engine: "2.5L Flat-4 / 2.4L Turbo", power: "182-260 HP", transmission: "CVT", fuelType: "Regular Gasoline" }, features: ["Symmetrical AWD", "EyeSight", "X-Mode", "Roof Rails"], isActive: true, featured: false },
    { name: "Forester", brand: "Subaru", category: "regular", price: "$26,000-$35,000", image: "/api/placeholder/600/400", info: "Compact SUV, 2.5L flat-4 (182 HP) | Versatile and capable", year: 2023, specifications: { engine: "2.5L Flat-4", power: "182 HP", transmission: "CVT", fuelType: "Regular Gasoline" }, features: ["Symmetrical AWD", "EyeSight", "X-Mode", "Cargo Space"], isActive: true, featured: false },
    { name: "WRX", brand: "Subaru", category: "regular", price: "$30,000-$40,000", image: "/api/placeholder/600/400", info: "Performance sedan, 2.4L turbo flat-4 (271 HP) | Rally-bred performance", year: 2023, specifications: { engine: "2.4L Turbo Flat-4", power: "271 HP", transmission: "6-Speed Manual / CVT", fuelType: "Premium Gasoline" }, features: ["Symmetrical AWD", "Sport-Tuned Suspension", "Performance Seats", "Track Mode"], isActive: true, featured: true },
    { name: "Crosstrek", brand: "Subaru", category: "regular", price: "$23,000-$30,000", image: "/api/placeholder/600/400", info: "Subcompact SUV, 2.0L flat-4 (152 HP) or 2.5L (182 HP) | Rugged and efficient", year: 2023, specifications: { engine: "2.0L Flat-4 / 2.5L Flat-4", power: "152-182 HP", transmission: "CVT / 6-Speed Manual", fuelType: "Regular Gasoline" }, features: ["Symmetrical AWD", "EyeSight", "X-Mode", "Ground Clearance"], isActive: true, featured: false },
    { name: "Legacy", brand: "Subaru", category: "regular", price: "$25,000-$35,000", image: "/api/placeholder/600/400", info: "Midsize sedan, 2.5L flat-4 (182 HP) or 2.4L turbo (260 HP) | Refined and capable", year: 2023, specifications: { engine: "2.5L Flat-4 / 2.4L Turbo", power: "182-260 HP", transmission: "CVT", fuelType: "Regular Gasoline" }, features: ["Symmetrical AWD", "EyeSight", "DriverFocus", "Premium Interior"], isActive: true, featured: false },

    // Kia
    { name: "K5", brand: "Kia", category: "regular", price: "$24,000-$35,000", image: "/api/placeholder/600/400", info: "Midsize sedan, 1.6L turbo (180 HP) or 2.5L turbo (290 HP) | Sporty design", year: 2023, specifications: { engine: "1.6L Turbo / 2.5L Turbo", power: "180-290 HP", transmission: "8-Speed Automatic", fuelType: "Regular Gasoline" }, features: ["Kia Drive Wise", "UVO Connect", "Wireless Charging", "Premium Audio"], isActive: true, featured: false },
    { name: "Sportage", brand: "Kia", category: "regular", price: "$26,000-$38,000", image: "/api/placeholder/600/400", info: "Compact SUV, 2.5L I4 (187 HP) or hybrid (227 HP) | Bold and efficient", year: 2023, specifications: { engine: "2.5L I4 / Hybrid", power: "187-227 HP", transmission: "8-Speed Automatic", fuelType: "Regular Gasoline / Hybrid" }, features: ["All-Wheel Drive", "Kia Drive Wise", "UVO Connect", "Panoramic Sunroof"], isActive: true, featured: false },
    { name: "Sorento", brand: "Kia", category: "regular", price: "$30,000-$45,000", image: "/api/placeholder/600/400", info: "Midsize SUV, 2.5L I4 (191 HP) or hybrid (227 HP) | Family-focused", year: 2023, specifications: { engine: "2.5L I4 / Hybrid", power: "191-227 HP", transmission: "8-Speed Automatic", fuelType: "Regular Gasoline / Hybrid" }, features: ["All-Wheel Drive", "Three-Row Seating", "Kia Drive Wise", "Captain's Chairs"], isActive: true, featured: false },
    { name: "Seltos", brand: "Kia", category: "regular", price: "$22,000-$30,000", image: "/api/placeholder/600/400", info: "Subcompact SUV, 2.0L I4 (146 HP) or 1.6L turbo (175 HP) | Urban-friendly", year: 2023, specifications: { engine: "2.0L I4 / 1.6L Turbo", power: "146-175 HP", transmission: "CVT / 7-Speed DCT", fuelType: "Regular Gasoline" }, features: ["All-Wheel Drive", "Kia Drive Wise", "UVO Connect", "LED Lighting"], isActive: true, featured: false },
    { name: "Telluride", brand: "Kia", category: "regular", price: "$36,000-$50,000", image: "/api/placeholder/600/400", info: "Large SUV, 3.8L V6 (291 HP) | Premium three-row SUV", year: 2023, specifications: { engine: "3.8L V6", power: "291 HP", transmission: "8-Speed Automatic", fuelType: "Regular Gasoline" }, features: ["All-Wheel Drive", "Captain's Chairs", "Harman Kardon Audio", "Kia Drive Wise"], isActive: true, featured: false },

    // Mazda
    { name: "Mazda3", brand: "Mazda", category: "regular", price: "$22,000-$30,000", image: "/api/placeholder/600/400", info: "Compact sedan or hatchback, 2.5L I4 (186 HP) | Premium feel", year: 2023, specifications: { engine: "2.5L I4", power: "186 HP", transmission: "6-Speed Manual / 6-Speed Automatic", fuelType: "Regular Gasoline" }, features: ["i-ACTIVSENSE", "Mazda Connect", "Premium Interior", "SKYACTIV Technology"], isActive: true, featured: false },
    { name: "CX-5", brand: "Mazda", category: "regular", price: "$26,000-$38,000", image: "/api/placeholder/600/400", info: "Compact SUV, 2.5L I4 (187 HP) or turbo (250 HP) | Driving dynamics", year: 2023, specifications: { engine: "2.5L I4 / 2.5L Turbo", power: "187-250 HP", transmission: "6-Speed Automatic", fuelType: "Regular Gasoline" }, features: ["i-ACTIV AWD", "i-ACTIVSENSE", "Bose Audio", "Premium Materials"], isActive: true, featured: false },
    { name: "CX-9", brand: "Mazda", category: "regular", price: "$35,000-$50,000", image: "/api/placeholder/600/400", info: "Midsize SUV, 2.5L turbo I4 (250 HP) | Three-row luxury", year: 2023, specifications: { engine: "2.5L Turbo I4", power: "250 HP", transmission: "6-Speed Automatic", fuelType: "Regular Gasoline" }, features: ["i-ACTIV AWD", "Three-Row Seating", "Bose Audio", "Captain's Chairs"], isActive: true, featured: false },
    { name: "MX-5 Miata", brand: "Mazda", category: "regular", price: "$28,000-$35,000", image: "/api/placeholder/600/400", info: "Sports car, 2.0L I4 (181 HP) | Pure driving joy", year: 2023, specifications: { engine: "2.0L I4", power: "181 HP", transmission: "6-Speed Manual / 6-Speed Automatic", fuelType: "Premium Gasoline" }, features: ["Rear-Wheel Drive", "Convertible Top", "Sport-Tuned Suspension", "Brembo Brakes"], isActive: true, featured: true },

    // Dodge
    { name: "Charger", brand: "Dodge", category: "regular", price: "$35,000-$50,000", image: "/api/placeholder/600/400", info: "Sedan, 3.6L V6 (292 HP) or 5.7L V8 (370 HP) | American muscle", year: 2023, specifications: { engine: "3.6L V6 / 5.7L V8", power: "292-370 HP", transmission: "8-Speed Automatic", fuelType: "Regular Gasoline" }, features: ["Performance Pages", "Uconnect", "Sport Mode", "Launch Control"], isActive: true, featured: true },
    { name: "Challenger", brand: "Dodge", category: "regular", price: "$30,000-$45,000", image: "/api/placeholder/600/400", info: "Coupe, 3.6L V6 (303 HP) | Retro muscle car", year: 2023, specifications: { engine: "3.6L V6", power: "303 HP", transmission: "8-Speed Automatic", fuelType: "Regular Gasoline" }, features: ["Performance Pages", "Uconnect", "Sport Suspension", "Heritage Design"], isActive: true, featured: true },
    { name: "Durango", brand: "Dodge", category: "regular", price: "$40,000-$60,000", image: "/api/placeholder/600/400", info: "Midsize SUV, 3.6L V6 (293 HP) or 5.7L V8 (360 HP) | Performance SUV", year: 2023, specifications: { engine: "3.6L V6 / 5.7L V8", power: "293-360 HP", transmission: "8-Speed Automatic", fuelType: "Regular Gasoline" }, features: ["All-Wheel Drive", "Three-Row Seating", "Tow Package", "Performance Pages"], isActive: true, featured: false },

    // Jeep
    { name: "Wrangler", brand: "Jeep", category: "regular", price: "$32,000-$60,000", image: "/api/placeholder/600/400", info: "Off-road SUV, 3.6L V6 (285 HP) or 2.0L turbo (270 HP) | Ultimate off-roader", year: 2023, specifications: { engine: "3.6L V6 / 2.0L Turbo", power: "270-285 HP", transmission: "6-Speed Manual / 8-Speed Automatic", fuelType: "Regular Gasoline" }, features: ["4x4 Capability", "Removable Doors", "Fold-Down Windshield", "Rock-Trac 4WD"], isActive: true, featured: true },
    { name: "Grand Cherokee", brand: "Jeep", category: "regular", price: "$38,000-$70,000", image: "/api/placeholder/600/400", info: "Midsize SUV, 3.6L V6 (293 HP) or 5.7L V8 (357 HP) | Premium capability", year: 2023, specifications: { engine: "3.6L V6 / 5.7L V8", power: "293-357 HP", transmission: "8-Speed Automatic", fuelType: "Regular Gasoline" }, features: ["Quadra-Trac 4WD", "Air Suspension", "Uconnect", "Tow Package"], isActive: true, featured: false },
    { name: "Renegade", brand: "Jeep", category: "regular", price: "$24,000-$30,000", image: "/api/placeholder/600/400", info: "Subcompact SUV, 2.4L I4 (180 HP) | Compact capability", year: 2023, specifications: { engine: "2.4L I4", power: "180 HP", transmission: "9-Speed Automatic", fuelType: "Regular Gasoline" }, features: ["Trail Rated 4x4", "Uconnect", "My Sky Roof", "Trailhawk Package"], isActive: true, featured: false },
    { name: "Compass", brand: "Jeep", category: "regular", price: "$26,000-$35,000", image: "/api/placeholder/600/400", info: "Compact SUV, 2.4L I4 (177 HP) | Urban adventure", year: 2023, specifications: { engine: "2.4L I4", power: "177 HP", transmission: "CVT / 9-Speed Automatic", fuelType: "Regular Gasoline" }, features: ["Trail Rated 4x4", "Uconnect", "Selec-Terrain", "Trailhawk Package"], isActive: true, featured: false },
    { name: "Gladiator", brand: "Jeep", category: "regular", price: "$38,000-$55,000", image: "/api/placeholder/600/400", info: "Midsize pickup, 3.6L V6 (285 HP) | Only open-air pickup", year: 2023, specifications: { engine: "3.6L V6", power: "285 HP", transmission: "6-Speed Manual / 8-Speed Automatic", fuelType: "Regular Gasoline" }, features: ["4x4 Capability", "Removable Doors", "Fold-Down Windshield", "Best-in-Class Towing"], isActive: true, featured: false },

    // Chrysler
    { name: "300", brand: "Chrysler", category: "regular", price: "$32,000-$45,000", image: "/api/placeholder/600/400", info: "Full-size sedan, 3.6L V6 (292 HP) or 5.7L V8 (363 HP) | Bold luxury", year: 2023, specifications: { engine: "3.6L V6 / 5.7L V8", power: "292-363 HP", transmission: "8-Speed Automatic", fuelType: "Regular Gasoline" }, features: ["All-Wheel Drive", "Uconnect", "Premium Interior", "Sport Mode"], isActive: true, featured: false },
    { name: "Pacifica", brand: "Chrysler", category: "regular", price: "$37,000-$55,000", image: "/api/placeholder/600/400", info: "Minivan, 3.6L V6 (287 HP) or plug-in hybrid (260 HP) | Family innovation", year: 2023, specifications: { engine: "3.6L V6 / Plug-in Hybrid", power: "260-287 HP", transmission: "9-Speed Automatic", fuelType: "Regular Gasoline / Plug-in Hybrid" }, features: ["Stow 'n Go Seating", "Uconnect Theater", "Hands-Free Doors", "Vacuum Cleaner"], isActive: true, featured: false },
    { name: "Voyager", brand: "Chrysler", category: "regular", price: "$30,000-$40,000", image: "/api/placeholder/600/400", info: "Minivan, 3.6L V6 (287 HP) | Affordable family hauler", year: 2023, specifications: { engine: "3.6L V6", power: "287 HP", transmission: "9-Speed Automatic", fuelType: "Regular Gasoline" }, features: ["Stow 'n Go Seating", "Uconnect", "Seven Passengers", "Cargo Space"], isActive: true, featured: false }
];

module.exports = { regularCars }; 